### ISSUE TITLE
nodejs install

### ISSUE THREAD

**Issue by sraddhanjali** [CodeCreed/disaster-broadcast#1]
```
nodejs install 
```

throws the following error. Please see to it.

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/home/tilaprimera/workspace/disaster-broadcast/install'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by rpidanny** [comment]
It's npm install not nodejs install

**Comment by sraddhanjali** [comment]
lol
